# Arquivo: ./prometheus/alternative/kubernetes-prometheus/clusterRole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # contem regras que representam um conjunto de permissoes
metadata:
  name: prometheus
rules:
- apiGroups: [""] # "" indica o grupo de API base
  resources:      # especifica os recursos suplicados
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding # concede as permissoes definidas em um papel para um usuario ou conjunto de usuarios
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: default
  namespace: monitoring
