# Arquivo: gitlab-runner-config.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config
data:
  config.toml: |-
     concurrent = 4
     [[runners]]
       name = "runner"
       url = "http://10.20.9.116:30036"
       id = 1
       token = "glrt-qJDS_pTGimZC8YtaoBPw"
       token_obtained_at = 2023-05-31T16:40:36Z
       token_expires_at = 0001-01-01T00:00:00Z
       executor = "kubernetes"
       [runners.kubernetes]
          poll_timeout = 600
          cpu_request = "1"
          service_cpu_request = "200m"
