# Arquivo: ./gitlab/services-integration-prometheus/integration-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: integration-service
spec:
  selector:
    app: gitlab
  type: NodePort
  ports:
    - name: node-exporter-metrics
      protocol: TCP
      port: 9100
      targetPort: 9100
      nodePort: 30086
    - name: gitlab-workhorse-metrics
      protocol: TCP
      port: 9229
      targetPort: 9229
      nodePort: 30087
    - name: gitlab-exporter-metrics
      protocol: TCP
      port: 9168
      targetPort: 9168
      nodePort: 30088
    - name: registry-metrics
      protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30089
    - name: sidekiq-metrics
      protocol: TCP
      port: 9168
      targetPort: 9168
      nodePort: 30090
    - name: redis-exporter-metrics
      protocol: TCP
      port: 9121
      targetPort: 9121
      nodePort: 30091
    - name: postgres-metrics
      protocol: TCP
      port: 9187
      targetPort: 9187
      nodePort: 30092
    - name: gitaly-metrics
      protocol: TCP
      port: 9236
      targetPort: 9236
      nodePort: 30093
    - name: pgbouncer-metrics
      protocol: TCP
      port: 9188
      targetPort: 9188
      nodePort: 30094
